spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/titan_tune
    username: titan_user
    password: titan_password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
